export const CATEGORIES = [
    "Science-Technology", 
    "Beauty",
    "Design-Tips",
    "History", 
    "Music", 
    "Technology", 
    "Education",
    "Sport", 
    "Fashion",
    "Life Style",
    "Travel",
    "Science",
    "Design",
    "Book",
    "Game",
    "Fitness",
    "Health",
    "Business",
    "Photograpy",
    "Art",
    "Food",
    "Careers",
    "Entertainment",
    "Computer-IT Business"
];